// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../rawFile.js")

type Info = GetInfo<{
  file: "./rawFile.ts",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/introduction.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/queries/ping.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/InCabinArea2x2.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/InCabinArea2x3.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/InCabinArea3x3.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/Vehicle.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/VehicleTrailer.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/VehicleTrailerAxle.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/VehicleTrailerWheel.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/TrailerWheelBrake.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/TrailerWheelTire.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/TrailerTag.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/TrailerAxleTag.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/objects/TrailerWheelTag.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/inputs/InCabinArea2x2Input.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/inputs/InCabinArea2x3Input.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/inputs/InCabinArea3x3Input.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/TwoRowsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/ThreeRowsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/TwoColumnsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/ThreeColumnsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/VehicleTrailerKindEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/ThreeTrailers.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/AxlePositionEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/TwoSides.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/EightOutsideInNumber.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Acceleration_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Angle_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Angularspeed_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Datetime_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Distancepervolume_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Duration_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Electriccharge_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Electriccurrent_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Energyconsumptionperdistance_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Force_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Frequency_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Illuminance_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Length_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Mass_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Massperdistance_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Masspertime_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Power_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Pressure_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Rating_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Relation_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Resistance_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Rotationalspeed_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Temperature_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Torque_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Velocity_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Voltage_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Volume_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Volumeflowrate_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Volumeperdistance_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/enums/Work_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/Int8.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/UInt8.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/Int16.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/UInt16.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/UInt32.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/Int64.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/trailer-domain-model/scalars/UInt64.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/llms.txt";
  module: typeof import("../rawFile.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }, false>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
}