// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../rawFile.js")

type Info = GetInfo<{
  file: "./rawFile.ts",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/introduction.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/vehicle.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/seat.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/getSeat.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/getSeatPosition.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/getSeatHeight.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/getSeatTilt.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/getSeatMassageLevel.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/queries/isSeatOccupied.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/mutations/setSeatPosition.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/mutations/setSeatHeight.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/mutations/setSeatTilt.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/mutations/setSeatMassageLevel.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/mutations/setSeatHeatingCooling.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/InCabinArea2x2.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Cabin.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Seat.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Airbag.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Backrest.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Headrest.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Seating.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/Vehicle.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/objects/VehicleIdentification.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/inputs/InCabinArea2x2Input.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/TwoRowsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/ThreeRowsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/TwoColumnsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/ThreeColumnsInCabinEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/DriverPositionEnum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/Angle_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/Length_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/enums/Relation_Unit_Enum.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/Int8.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/UInt8.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/Int16.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/UInt16.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/UInt32.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/Int64.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/api/seat-capabilities/scalars/UInt64.md";
  module: typeof import("../rawFile.js");
}] | [{
  id: "root";
  module: typeof import("../root.js");
}, {
  id: "/llms.txt";
  module: typeof import("../rawFile.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }, false>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
}