name: ci

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: uv
        uses: astral-sh/setup-uv@v7

      - name: npm install gql-inspector
        run: npm i --global @graphql-inspector/cli graphql

      - name: sync
        run: |
          uv sync --frozen

      - name: pre-commit
        run: |
          uv run pre-commit run --all-files

      - name: gitlint
        run: |
          # Determine base branch - use PR base if in PR, otherwise main
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_BRANCH="${{ github.base_ref }}"
          else
            BASE_BRANCH="main"
          fi
          echo "Using base branch: $BASE_BRANCH"
          # Run gitlint on commits since base branch
          uv run gitlint --commits $(git merge-base HEAD origin/$BASE_BRANCH)..HEAD

      - name: mypy
        run: |
          uv run mypy src/ tests/

      - name: test
        run: |
          uv run nox
